# Generated by Django 2.1.7 on 2019-04-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('profilepic', models.ImageField(upload_to=manager.models.Interndocs)),
                ('document', models.FileField(upload_to=manager.models.Interndocs)),
                ('stipend', models.FloatField()),
                ('date_of_join', models.DateField()),
                ('date_of_leave', models.DateField()),
                ('admin_remark', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internadmin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
